name: /scratch/scholar/chan1225/conda/envs/supdepth
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=openblas
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - certifi=2025.10.5=py310h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - freetype=2.13.3=h4a9f257_0
  - icu=73.1=h6a678d5_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - ittapi=3.26.4=py310hea6c23e_0
  - ittapi-static=3.26.4=hecca717_0
  - jpeg=9f=h5ce9db8_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=15.2.0=h767d61c_7
  - libhwloc=2.12.1=default_h3d81e11_1000
  - libnsl=2.0.0=h5eee18b_0
  - libopenblas=0.3.30=h46f56fc_0
  - libpng=1.6.50=h2ed474d_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libtiff=4.5.1=hffd6297_1
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - mkl=2025.0.0=hacee8c2_941
  - ncurses=6.5=h7934f7d_0
  - numpy-base=2.2.5=py310hf387b04_2
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.5.4=h26f9b46_0
  - pillow=10.3.0=py310h5eee18b_0
  - pip=25.2=pyhc872135_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - python_abi=3.10=2_cp310
  - readline=8.3=hc2a1206_0
  - scipy=1.15.3=py310ha592af2_1
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tbb=2022.3.0=h8d10470_0
  - tbb-devel=2022.3.0=h74b38a2_0
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - anyio==4.11.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - click==8.3.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - exceptiongroup==1.3.0
      - filelock==3.19.1
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - fvcore==0.1.5.post20221221
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.0.1
      - idna==3.11
      - imageio==2.37.0
      - iopath==0.1.10
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - lightning-utilities==0.15.2
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - mmcv==1.7.2
      - mpmath==1.3.0
      - multidict==6.7.0
      - networkx==3.3
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python==4.12.0.88
      - packaging==25.0
      - path==17.1.1
      - path-py==12.5.0
      - platformdirs==4.5.0
      - portalocker==3.2.0
      - propcache==0.4.1
      - protobuf==6.33.0
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.1.4
      - pytorch3d==0.7.6
      - pyyaml==6.0.3
      - rich==14.2.0
      - safetensors==0.6.2
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.2.0
      - timm==0.9.16
      - tomli==2.3.0
      - torch==2.3.0+cu121
      - torchmetrics==1.8.2
      - torchvision==0.18.0+cu121
      - tqdm==4.67.1
      - triton==2.3.0
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - werkzeug==3.1.3
      - yacs==0.1.8
      - yapf==0.43.0
      - yarl==1.22.0
prefix: /scratch/scholar/chan1225/conda/envs/supdepth
